apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::589587136057:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RZS106PYFTNK
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::589587136057:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
        - system:bootstrappers
        - system:nodes
  mapUsers:  |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-18T10:21:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "2376"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0f879645-6d51-493e-b71d-c7918105c61f
